### ISSUE TITLE
reuse connection settings provided by SonarQube.Analysis.xml

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#16]
Typically the connection to the SQ instance is defined in SonarQube.Analysis.xml and should not be part of any build script. The wrapper uses a default setting if the SQ URL is not set and does not reuse the SonarQube.Analysis.xml connection settings.

```
C:\Builds\5\CUDA samples\CxxSQMsBuildRunner CudaSamples_vs2013\src>C:\SQTools\CxxSonarQubeMsbuidRunner\CxxSonarQubeMsbuidRunner.exe /k:CudaSamples /n:"CudaSamples" /v:7.5 /m:Samples_vs2013.sln
[|"/k:CudaSamples"; "/n:CudaSamples"; "/v:7.5"; "/m:Samples_vs2013.sln"|]
[Install] : C:\ProgramData\chocolatey\choco.exe install python2 -y
[Install] : C:\ProgramData\chocolatey\choco.exe install cppcheck -y
url not specified. using default: http://localhost:9000
login not specified. using default: admin
password not specified. using default: admin
###################################
########## Begin Stage  ###########
###################################
[Execute] : C:\ProgramData\MSBuidSonarQube\1.0.2\MSBuild.SonarQube.Runner.exe begin /d:sonar.verbose=true /d:sonar.host.url=http://localhost:9000 /d:sonar.login=admin /d:sonar.password=xxxxx /k:CudaSamples /n:CudaSamples /v:7.5   /s:C:\Users\Administrator\AppData\Local\Temp\2\tmpC177.tmp
```

**Comment by jmecosta** [comment]
are you manually modifying the one in C:\ProgramData\MSBuidSonarQube\1.0.2 ? by default the url in that xml is http://localhost:9000. but i dont see any reason why i cant pick the cred and url after the runner is installed.

**Comment by jmecosta** [comment]
by the way its not safe to keep those credentials, at least use and pass in a file in disk. url its something else. but i guess when you change the server then you will run into issue if you have many agents to change?

**Comment by Bertk** [comment]
I use the SQ encryption for the password and restrict access with Windows ACL permissions on the build systems. The update will be done by administrative scripts anyway. 
Yes, I use the SonarQube.Analysis.xml and update the connection setting only within this file 
(see chapter **Setup of the MSBuild SonarQube Runner on the Build Agent Machine** in http://redirect.sonarsource.com/doc/sq-setup-guide-for-dotnet-users.html).

**Comment by jmecosta** [comment]
should be handled in new release:
https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases/download/1.4/CxxSonarQubeMsbuidRunner.zip
