### ISSUE TITLE
Wrapper fails to install tools on TFS build client

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#18]
The TFS build account does not have administrator rights and the installation of tools fails (see attached build log file).
[build-log-extract.txt](https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/files/75431/build-log-extract.txt)

I recommend to create a configuration parameter for the _tools auto install feature_ which is very nice for the developer desktop systems but not acceptable in a configuration management environment (ensure  reproducibility).

**Comment by jmecosta** [comment]
related with #2 

i will add a the possibility to read a xml with input data in format:

`
 <settings>
  <cppcheckpath></cppcheckpath>
  <ratspath></ratspath>
 </settings>
`

**Comment by jmecosta** [comment]
should be handled in new release:
https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases/download/1.4/CxxSonarQubeMsbuidRunner.zip

**Comment by jmecosta** [comment]
@Bertk please give  a try to new version, the  format from the user file can be seen in the command line help
