### ISSUE TITLE
Documentation for helper tools

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#19]
There some helper tools which are used implicitly and not mentioned anywhere e.g. python2, chocolatey. Please add  a list of tools in a "Readme.txt" or "License.txt"

**Comment by jmecosta** [comment]
i will, i havent got much time to document this at all. but will do

**Comment by jmecosta** [comment]
readme improve to be less confusing and make the wrapper the main application that is provided by this repository
