### ISSUE TITLE
CxxSonarQubeMsbuidRunner cannot be executed offline

### ISSUE THREAD

**Issue by alustrement** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#2]
Even after a succesfull online analysis, it's impossible to run an offline analysis.
It's also a bite difficult to install dependencies without chocolatey, my manual python installation was never recognised.

**Comment by jmecosta** [comment]
hi, thanks for trying it out.

what version are you trying the offline analysis? that python thing it might be a issue that i need to figure out. i created a new issue

**Comment by jmecosta** [comment]
created #4

**Comment by jmecosta** [comment]
offline, you mean connected to internet?

**Comment by alustrement** [comment]
I'm using the 1.0 RC1. Yes, by offline I mean without internet connection.

**Comment by jmecosta** [comment]
yeah, i know... i can try to handle as soon as possible. or if you want you can create a pr. i will merge it

**Comment by jmecosta** [comment]
should be handled in new release:
https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases/download/1.4/CxxSonarQubeMsbuidRunner.zip
