### ISSUE TITLE
Useless definitions in FSharp.Core.xml

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#20]
There are many useless statements in packages\CppCheckTask.1.0.4\build\FSharp.Core.xml. This should be avoided.

``` xml
<members>
<member name="">

</member>
<member name="">
```

**Comment by jmecosta** [comment]
should be handled in new release:
https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases/download/1.4/CxxSonarQubeMsbuidRunner.zip
