### ISSUE TITLE
mixedup logging message

### ISSUE THREAD

**Issue by Bertk** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#22]
This might be a problem within the logging and the handling of '\' and '\t' might be special character 'tab'.
Please also add a space between path and message. Cxx plug-in uses ' ' to indicate a parameters and this would be nice for this messages, too. 

```
[Install] Failed to install python, likely it will fail. please install manually python to c:○ools\python2[Install] : C:\ProgramData\chocolatey\choco.exe install cppcheck -y

[Install] Failed to install cppcheck, likely it will fail. please install manually python to C:\Program Files (x86)\Cppcheckurl not specified. using default: http://localhost:9000
```

**Comment by jmecosta** [comment]
new release:
https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases/download/1.4/CxxSonarQubeMsbuidRunner.zip
