### ISSUE TITLE
1.0-RC1 source code doesn't compile as is

### ISSUE THREAD

**Issue by alustrement** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#3]
Multiple errors:
Error   2   The mutable variable 'ouputFilePath' is used in an invalid way. Mutable variables cannot be captured by closures. Consider eliminating this use of mutation or using a heap-allocated mutable reference cell via 'ref' and '!'. C:\Users\zdxh6864\Downloads\sonar-cxx-msbuild-tasks-master\sonar-cxx-msbuild-tasks-master\CppTasks\VeraTask\VeraTask.fs 95  13  VeraTask

I'm not used to code with F# but following the project description I use the correct .NET Framework (4.5.2) and F# runtime (3.1), so what's the point ?

**Comment by jmecosta** [comment]
you need visual studio 2015 or fsharp 4.0. that issue has been fixed in 4.0

**Comment by alustrement** [comment]
Ok, thanks it's better :)
Maybe you should update fsproj and sln. Latest commit still reference VS2013:
https://github.com/SonarOpenCommunity/sonar-cxx-msbuild-tasks/blob/master/MSBuildTasks.sln

**Comment by jmecosta** [comment]
done thanks

**Comment by alustrement** [comment]
I'm still expecting issues with the MSBuild task :/
I move the project to FSharp.Core 4.0.0.0 and update all bindingRedirect rules in app.config but it always looking for the 4.3 dll. Any idea ?

```
error MSB4062: Impossible de charger la tâche "CpplintTask" à partir de l'assembly C:\Sandbox\sonar-cxx-msbuild-tasks-master\CxxSonarQubeMsbuidRunner\bin\Debug\CpplintTask.dll. Impossible de charger le fichier ou l'assembly 'FSharp.Core, Version=4.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou une de ses dépendances. Le fichier spécifié est introuvable. Assurez-vous que la déclaration <UsingTask> est correcte, que l'assembly et toutes ses dépendances sont disponibles et que la tâche contient une classe publique qui implémente Microsoft.Build.Framework.ITask
```

**Comment by jmecosta** [comment]
Show me your app config content. You should point to 4.3.1

**Comment by alustrement** [comment]
When I use the default app.config with the 4.3.1, I have the same issue. MS Build task looks for the 4.3.0.

**Comment by jmecosta** [comment]
Can you check with ilspy what reference is using 4.3.0 in cpplinttask.

I suppose this happens when you compile the project?

**Comment by jmecosta** [comment]
actuall let me try to fix the build in appveyour

**Comment by jmecosta** [comment]
Can you get latest and try build it again. I still need to fix the tests
but it should compile now

**Comment by jmecosta** [comment]
can you confirm this works:

https://ci.appveyor.com/api/buildjobs/avy5n4j6j386ftls/artifacts/CxxSonarQubeMsbuidRunner.zip

**Comment by alustrement** [comment]
Thanks, but these binairies don't work. Same issue, CpplintTask try to call the 4.3 FSharpCore assembly.
ILDASM confirms that dll is actually linked to the 4.3 :
assembly extern FSharp.Core
{
  .publickeytoken = (B0 3F 5F 7F 11 D5 0A 3A ) 
  .ver 4:3:0:0
}

**Comment by jmecosta** [comment]
Yep, try again. I think I've fixed it

**Comment by alustrement** [comment]
Indeed, latest sources works ;-)

**Comment by jmecosta** [comment]
great, thanks for testing. latest binaries are found are in the artifacts in https://ci.appveyor.com/project/SonarOpenCommunity/sonar-cxx-msbuild-tasks
