### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by sawilde** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#37]
Getting the following error when running the build on AppVeyor - The agent probably does not have the appropriate issue.

```
   [exec] [Execute] : "C:\Program Files (x86)\MSBuild\12.0\Bin\MSBuild.exe" "C:\projects\opencover\main\opencover.sln" /v:Detailed /p:SonarQubeTempPath="C:\projects\opencover\main\.sonarqube" /p:Configuration=release,Platform=x
64,GtestRunnerTaskEnabled=false /t:Clean;Build /l:FileLogger,Microsoft.Build.Engine;logfile=C:\projects\opencover\main\.cxxresults\BuildLog.txt 
     [exec] 
     [exec] [CxxSonarQubeMsbuidRunner] The following msbuild processes have been found: 
     [exec] [CxxSonarQubeMsbuidRunner] The following msbuild processes have been found after running analysis: 
     [exec] 3564 : MSBuild
     [exec] Will Kill : 3564 : MSBuild
     [exec] Exception During Run: Access is denied 
     [exec]     at System.Diagnostics.Process.Kill()
     [exec]    at SonarRunnerPhases.RunBuild(OptionsData options) in C:\projects\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\SonarRunnerPhases.fs:line 266
     [exec]    at Program.main(String[] argv) in C:\projects\sonar-cxx-msbuild-tasks\CxxSonarQubeMsbuidRunner\Program.fs:line 40

BUILD FAILED

C:\projects\opencover\default.build(123,6):
External Program Failed: C:\projects\opencover\tools\sonarqube\cxx-runner\CxxSonarQubeMsbuidRunner.exe (return code was 1)

Total time: 579.5 seconds.
```

Q. Why do you need to kill the process and/or what happens if you don't kill the process?

**Comment by jmecosta** [comment]
in local builds, if i use VSSonarExtension then those msbuilds that are left running prevent us from building the project becasue they lock some sonar targets files that are supposed to be deleted after you execute the analysis.

in appveyour there is not needed for this, the appveyour agent should handle those for you. so i can just 
1. add argument to skip kill
2. or swallow the exception and continue,

what do you prefer?

**Comment by jmecosta** [comment]
try this https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases/download/1.9.1-RC2/CxxSonarQubeMsbuidRunner.zip

**Comment by sawilde** [comment]
The issue is not resolved as the code throwing the exception was not wrapped by the swallow-exception code committed in https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/commit/e5c071694c75738db0f8af31c20e2ef2c7a4b4d7

e,g,

```
            printf "Will Kill : %s" (sprintf "%s : %s\r\n" (processdata.Id.ToString()) processdata.ProcessName)
            processdata.Kill()   // <-- crash is happening here
            processdata.WaitForExit(2000) |> ignore
```

**Comment by jmecosta** [comment]
ok thanks for the quick fix, its merged. I will make a new release soon

**Comment by jmecosta** [comment]
https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases/download/1.9.1/CxxSonarQubeMsbuidRunner.zip release. thanks

**Comment by jmecosta** [comment]
@sawilde please reopen if still issue.

**Comment by sawilde** [comment]
All is well 

I was going to come back and close one I had integrated your final change; I am currently using an earlier build (zip) with an assembly with my modifications copied over the top of it.

**Comment by jmecosta** [comment]
good to hear, by the way, did you manage to import the visual studio code analysis issues into sonar? i think it was your initial issue?

**Comment by sawilde** [comment]
I did - http://sonar.many-monkeys.com:9000/overview?id=719 - it's all part of the OpenCover project; SonarQube actually consumes coverage reports generated by OpenCover.

**Comment by jmecosta** [comment]
thats cool, saw that you got the cppcheck issues resolved already so the reporting is working properly. we also use your  tool :) in our company (thanks by the way) and we automate also the coverage creation with opencover and nunit, infact the cxx runner is prepared for that. the only thing you need to do is to install this nuget package : https://www.nuget.org/packages/NunitRunnerTask/ into the test projects that coverage and unit tests will be automatically imported into sonar

**Comment by sawilde** [comment]
I did look at the package but you embed OpenCover inside it whereas I like to use the latest release of OpenCover (current build) as I like to dogfood my own code.

However you really shouldn't embed other projects like this especially when they have their own nuget packages - your version of OpenCover could get out of date and could leave you users confused as to why running OpenCover on the command line from our package has different results to your results if they do not realize they have two version installed.

**Comment by jmecosta** [comment]
yes i agree, for us it works since we control nunit and opencover versions. i usually release those ones when we need. 

to support your use case, the targets file provided in the nuget package allows you to specify where the OpenCover.Console.exe is found.

```
  <PropertyGroup>
    <AssemblyExtension>.dll</AssemblyExtension>
    <ProduceCoverage    Condition="'$(ProduceCoverage)' == ''">false</ProduceCoverage>
    <Processor          Condition="'$(Processor)' == ''">x64</Processor>
    <TestRunner         Condition="'$(TestRunner)' == ''">Nunit</TestRunner>
    <OutputReportPaths  Condition="'$(OutputReportPaths)' == ''">$(SolutionDir)</OutputReportPaths>
    <DisableRetry       Condition="'$(DisableRetry)' == ''">true</DisableRetry>    
    <OpenCoverPath      Condition="'$(OpenCoverPath)' == ''">$(MSBuildThisFileDirectory)OpenCover\OpenCover.Console.exe</OpenCoverPath>
    <NunitPath          Condition="'$(NunitPath)' == ''">$(MSBuildThisFileDirectory)Nunit</NunitPath>
    <XunitPath          Condition="'$(XunitPath)' == ''">$(MSBuildThisFileDirectory)xunit.net</XunitPath>

    <NunitTestFilter    Condition="'$(NunitTestFilter)' == ''"></NunitTestFilter>
    <BreakBuildOnFailedTests    Condition="'$(BreakBuildOnFailedTests)' == ''">true</BreakBuildOnFailedTests>
    <AssembliesToTest   Condition="'$(AssembliesToTest)' == ''">$(OutputPath)$(AssemblyName)$(AssemblyExtension)</AssembliesToTest>
    <AssemblyName       Condition="'$(AssemblyName)' == ''">data</AssemblyName>
    <NunitTSServer       Condition="'$(NunitTSServer)' == ''">$(MSBuildThisFileDirectory)NunitTSServer\NunitTSServer.exe</NunitTSServer>
    <TSModelFolder       Condition="'$(TSModelFolder)' == ''"></TSModelFolder>
    <TSBinFolder       Condition="'$(TSBinFolder)' == ''"></TSBinFolder>
    <DontKillTs       Condition="'$(DontKillTs)' == ''">false</DontKillTs>
  </PropertyGroup>
```

as you can see, this is really not a general package usage since it contains some specific things. but however can be used in a more general case also.

Just to make less confusion this package is not refereed anywhere in the wrapper, just let you know this is possible
