### ISSUE TITLE
Do Not Dump Environment Variables During Build

### ISSUE THREAD

**Issue by sawilde** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#38]
During the build I noticed that the runner dumps the environment variables to the console/log.

On most CI systems environment variables are sometimes used to pass credentials; even when these credentials were originally encrypted they would be exposed when the environment variables were dumped.

I have mitigated the issue with my script but it was frustrating having to spin affected credentials.

**Comment by jmecosta** [comment]
we pass credentials via command line arguments, if you do like that the pass will me masked. in teamcity at least we can check environment variables. but i will change this. ive added just for debugging purposes.

**Comment by jmecosta** [comment]
try this https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases/download/1.9.1-RC2/CxxSonarQubeMsbuidRunner.zip

**Comment by sawilde** [comment]
the env-vars are no longer being dumped
