### ISSUE TITLE
Link to download the build fails

### ISSUE THREAD

**Issue by stephanerenou** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#40]
On your main page https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks you show this link: https://ci.appveyor.com/api/buildjobs/avy5n4j6j386ftls/artifacts/CxxSonarQubeMsbuidRunner.zip that does not appear to be valid anymore.

I don't know what link should replace this as you indicated later that one:
https://github.com/jmecsoftware/sonar-cxx-msbuild-tasks/releases/download/1.9.1/CxxSonarQubeMsbuidRunner.zip

**Comment by jmecosta** [comment]
alright the links to artifacts are having some id. so cannot be used to reflect the latest. updated to open the artifact page instead that seems to be always the same.

thanks for the heads up.
