### ISSUE TITLE
Can't use CxxRunner with nemo.sonarsource.org

### ISSUE THREAD

**Issue by sawilde** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#54]
nemo.sonarsource.org uses tokens in the `/d:sonar.login` and so there is no `/d:sonar.password` field required however the build runner defaults this to option to `admin` if not supplied.

Also because the token is also the password we should refrain from dumping this information to the console and treat it as sensitive data.

**Comment by jmecosta** [comment]
tought i add that thing implemented. i will check. should be easy fix

**Comment by jmecosta** [comment]
by the way, you should be able to use c++ plugin from nemo. and i far as i saw they do have some wrapper already going on. i havent tried however you might not need this anymore

**Comment by sawilde** [comment]
:) baby steps

**Comment by sawilde** [comment]
I've had a go at fixing it by allowing the use of a _pseudo_ switch `sonar.token` that will set the username to the token and the password to blank and then use a another flag to stop the default password form being added or supplied to the Sonar Build Runner exe

**Comment by jmecosta** [comment]
looks good, make pr i will merge it. thanks. got myself in the middle of other stuff meanwhile

**Comment by jmecosta** [comment]
@sawilde after checking this a bit better, i opted to use the /sonar.login=token since its the way the sonar  scanner works and visual studio extension (plus there are already 2 many switchs there :)). you can get latest release 1.9.5 and try out. should work

**Comment by sawilde** [comment]
no worries - I just wanted to spike out a possibility for you as I was not familiar with the code.
