### ISSUE TITLE
Exception During Run: The parameter is incorrect

### ISSUE THREAD

**Issue by mikehart526** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#71]
at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
--
25-Feb-2020 21:11:21 | at System.Diagnostics.Process.Start()
25-Feb-2020 21:11:21 | at MsbuildUtilityHelpers.CommandExecutor.MsbuildUtilityHelpers-ICommandExecutor-ExecuteCommand(String program, String args, FSharpMap`2 env, String wd) in E:\prod\OtherDevelopment\SonarQube\jmecsoftware\SonarPlugins\CxxSonarQubeRunner\MsbuildTaskUtils\IExecutor.fs:line 107
25-Feb-2020 21:11:21 | at SonarRunnerPhases.RunBuild(OptionsData options) in E:\prod\OtherDevelopment\SonarQube\jmecsoftware\SonarPlugins\CxxSonarQubeRunner\CxxSonarQubeRunner\SonarRunnerPhases.fs:line 326
25-Feb-2020 21:11:21 | at Program.main(String[] argv) in E:\prod\OtherDevelopment\SonarQube\jmecsoftware\SonarPlugins\CxxSonarQubeRunner\CxxSonarQubeRunner\Program.fs:line 47

Getting the above error when trying to run the scanner.

Command to run:
C:\CxxSonarQubeRunner\win-x64\CxxSonarQubeRunner.exe /x:vs19 /k:Project 1 /n:"Project1" /v:6.5 /d:sonar.host.url=https://sonar.company.tools /d:sonar.login=******** /m:ProjectProject1.sln /p:Configuration=Debug /p:Platform="Any CPU"

**Comment by jmecosta** [comment]
Make sure u have msbuild installed in the default locations

**Comment by mikehart526** [comment]
It runs fine with the vs17 MSBuild version and the only difference I can find is 2017 is Professional and 2019 is Enterprise.  Any way to specify which edition is installed?

**Comment by taustin73** [comment]
I am having the same issue and here is my location for msbuild:

C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe

**Comment by taustin73** [comment]
Also wondering if a similar issue is seen here: https://github.com/godotengine/godot/issues/27269 for a different application.

**Comment by mikehart526** [comment]
Did a little more digging to see if I could help at all(though I know next to nothing about f#) and the best I can tell, Process.Start isn't liking the ProcessStartInfo being set in IExecutor.fs

**Comment by jmecosta** [comment]
@taustin73 there was 3.2.0 version in draft can u try with that!

**Comment by jmecosta** [comment]
@mikehart526 can u try 3.2.1 and call the wrapper with /h and send me the agent cabilities. i susepect 3.2.1 will also work!
