### ISSUE TITLE
does 3.5.0 supported on VS 2022

### ISSUE THREAD

**Issue by arunselvaraj02** [SonarOpenCommunity/sonar-cxx-msbuild-tasks#76]
Hi, 

I followed the sonar commands as suggested and ended up with the error below. any help would be appreciated.

![image](https://github.com/user-attachments/assets/93fca118-aadc-4187-adf2-a06ff8b07dcc)

**Comment by jmecosta** [comment]
we are using it with vs2022 add the swtich to console as:  /x:vs22

**Comment by arunselvaraj02** [comment]
Thank you
